FROM python:3.10.12-slim-bookworm
ENV PYTHONDONTWRITEBYTECODE 1

RUN apt update && apt install -y git

WORKDIR /app

ENV VIRTUALENVPATH = /venv

COPY requirements.txt .

RUN python -m venv $VIRTUALENVPATH

ENV PATH $VIRTUALENVPATH/bin:$PATH

RUN pip install --upgrade pip

# ENTRYPOINT [ "/bin/bash" ]